# Read a JSON file generated by RoadProcessor, and output a csv file with time,speed
import json
import sys

with open(sys.argv[1]) as f:
	j = json.loads(f.read())

print("time,speed")
for el in j["speeds"]:
	print("{},{}".format(el[0], el[1]))

